Enhancement 52 - Allow query record as json
jetstreamapp/jetstream pull request #307
Opened 2023-04-14 18:39 UTC by joiecosby

This PR is working through the following issue: https://github.com/jetstreamapp/jetstream/issues/52

I updated the record action section to now include a copy from JSON button and the corresponding functionality. I know there hasn't been any record action functionality added to sub-queries but I added the 'json' functionality for future use just in case.

Below is a screenshot of the UI with the update:
![image](https://user-images.githubusercontent.com/39092797/232129421-590f4442-ba65-4d51-9bdb-ccdd310c1ff8.png)

2023-04-14 23:50 UTC, paustint requested changes

2023-04-14 23:50 UTC, paustint commented on libs/ui/src/lib/data-table/DataTableRenderers.tsx
> +        <Icon type="utility" icon="copy_to_clipboard" className="slds-button__icon " omitContainer />
@joiecosby - Can we remove the extra space `className="slds-button__icon "` (also for the line above which was probably the source of the copy paste)

2023-04-14 23:50 UTC, paustint commented on apps/jetstream/src/app/components/query/QueryResults/QueryResults.tsx
> +import copyToClipboard from 'copy-to-clipboard';
Can you make sure to run OrganizeImports in VScode? It may change the order and I try to keep them sorted. I should probably add format on save to the vscode settings file for the repo.

![image](https://user-images.githubusercontent.com/5461649/232171523-ba408360-69e6-41a5-aace-aebc4377d8c5.png)

2023-04-15 15:08 UTC, paustint commented
@joiecosby - After thinking on this a bit, I actually don't know if this is a great feature to add on in this way since the user can already right click and copy the row as JSON.

BUT what I think might be valuable is to view the record as JSON instead of copy. There is a component `<ViewEditCloneRecord />` (which is used in 3 places in the app) where I think might be a better location to allow the user to view as JSON.

Here is what I am thinking (but open to better ideas as well)
* Add button in the modal footer "View as JSON"
* Once clicked, the modal body view changes to a read-only code editor and shows the record
* The buttons at the bottom of the page should change ("View as JSON" should be replaced with "View Record" or something)
* I think the easiest way would be to add in one more `setState` variable - something like `viewMode: 'STANDARD' | 'JSON'` and that controls the view mode.
* If viewMode is JSON then instead of showing `<UiRecordForm` you would need to show a new component that you will need to create e.x. `ViewRecordEditor` (maybe you don't even need a new component - something to figure out)

### Existing feature which is basically the same
![image](https://user-images.githubusercontent.com/5461649/232232557-80231ac3-4836-4cf4-ab37-72b892f5842c.png)

### This might be a better place for this to live
![image](https://user-images.githubusercontent.com/5461649/232232623-185a228a-e13f-4d7d-ae3e-7b8092c59c6c.png)

2023-04-15 15:32 UTC, joiecosby commented
Closing this PR since the requirements for the issue has changed and this PR is from a forked repo.

2023-04-15 15:32 UTC, closed without merging