resolves #52
jetstreamapp/jetstream pull request #311
Opened 2023-04-15 20:00 UTC by joiecosby

This PR is working through the following issue: https://github.com/jetstreamapp/jetstream/issues/52

Added a new button to the View Record record action called View as JSON. Once you click on the button you should be redirected to a view of the record as json with updated buttons to copy to clipboard and a view record (which will take you back to the previous View Record modal).

Below is a screenshot of the UI with the update:
![Screen Shot 2023-04-15 at 12 56 45](https://user-images.githubusercontent.com/39092797/232250792-77ee7a2c-effb-40f3-8285-35282dc4600a.png)
![Screen Shot 2023-04-15 at 12 56 33](https://user-images.githubusercontent.com/39092797/232250793-6a0a8143-316c-4ac8-aef1-cecd3ac2ffbf.png)

2023-04-16 14:59 UTC, paustint requested changes

2023-04-16 14:59 UTC, paustint commented on apps/jetstream/src/app/components/core/ViewEditCloneRecord.tsx
> +                  <button
@joiecosby - I was thinking that we should have this button be the first button (all the way to the left) instead of next to close.

2023-04-16 14:59 UTC, paustint commented on apps/jetstream/src/app/components/core/ViewEditCloneRecord.tsx
> +                    <Icon type="utility" icon="preview" className="slds-button__icon slds-button__icon_left" omitContainer />
What do you think about using the icon `merge_field`? (Note this is a new icon, so you would need to add it to `icon-factory`
![image](https://user-images.githubusercontent.com/5461649/232320391-2055863c-294b-4d86-8206-2026a97ca0d6.png)

2023-04-16 14:59 UTC, paustint commented on apps/jetstream/src/app/components/core/ViewEditCloneRecord.tsx
> +  const [buttonState, setButtonState] = useState(() => getButtonState(action));
@joiecosby - I was initially thinking a little different here - this implementation is probably fine, but now there are two versions of the same state so it is probably more complicated than it needs to be.

I was thinking something like:
* don't add `json` as an action - I think the JSON can be grouped into the "View" action as just a minor variation
  * One main driver for this is that `UiRecordForm` uses `action: CloneEditView` but does not actually handle that case.
* `const [isViewAsJson, setIsViewAsJson] = useState(false);`
* Then all logic in the component about what to show can remain untouched except the one new button will be added to the `action === 'view'` section AND then a conditional would be wrapped around the button `{!isViewAsJson && <button>...`
* `{!loading && initialRecord && !isViewAsJson && ( <UiRecordForm ...`
* `{!loading && initialRecord && isViewAsJson && ( <div><Editor ...`

2023-04-16 14:59 UTC, paustint commented on apps/jetstream/src/app/components/core/ViewEditCloneRecord.tsx
> +    setButtonState(getButtonState(action));
If you take my prior suggestion, then here you would want to reset `setIsViewAsJson(false)` any time action changes.

2023-04-17 00:12 UTC, joiecosby commented on apps/jetstream/src/app/components/core/ViewEditCloneRecord.tsx
> +  const [buttonState, setButtonState] = useState(() => getButtonState(action));
@paustint how do you feel about this updated UI? The button layouts stays the same expect the _View as JSON_ and _Copy to Clipboard_ buttons. Since they are both dynamic, there is a conditional statement wrapped around both buttons.


![Screen Shot 2023-04-16 at 17 08 05](https://user-images.githubusercontent.com/39092797/232351463-8e9a3aef-2663-4d4d-bb37-1b36f9327c55.png)
![Screen Shot 2023-04-16 at 17 07 52](https://user-images.githubusercontent.com/39092797/232351466-c38cf821-f62f-4536-a1e9-e98d9e28efaf.png)

2023-04-17 02:41 UTC, paustint requested changes
@joiecosby We should probably just leave "copy to clipboard" on both views (with same results - copy JSON version of record).

<img width="806" alt="image" src="https://user-images.githubusercontent.com/5461649/232364318-515dac63-4bfb-414d-ab64-b8b1032cc30e.png">

2023-04-18 01:05 UTC, paustint approved these changes

2023-04-18 01:05 UTC, merged