[WIP] Improve data load error message
jetstreamapp/jetstream pull request #341
Opened 2023-05-02 01:33 UTC by joiecosby

PR resolves https://github.com/jetstreamapp/jetstream/issues/329

When the user clicks on the error icon, the content inside the tooltip will update to let the user know that error message was coped.

2023-05-02 01:38 UTC, joiecosby commented on libs/ui/src/lib/widgets/TooltipCopyToClipboard.tsx
@paustint a few questions for you:
1. How do you feel about the name of the component?
2. Should the component be more dynamic? At the moment, I am only passing the error messages but not passing in the icon. Should I allow the component to be dynamic like CopyToClipboard?

```
                        <CopyToClipboard
                          icon={{ type: 'utility', icon: 'error', description: 'load error' }}
                          content={row._errors}
                          className="slds-text-color_error slds-p-right_x-small"
                        />
```
3. Should I be using useRender() instead of useEffect()?

2023-05-02 15:13 UTC, paustint commented on libs/ui/src/lib/widgets/TooltipCopyToClipboard.tsx
@joiecosby - I would probably name it something like `CopyToClipboardWithTooltip` just so it is sorted right next to the other component and would be easier to find if a developer starts typing `<CopyTo...`

(see comment below first, but FYI this is not correct)
```diff
-export const TooltipCopyToClipboard: FunctionComponent<TooltipCopyToClipboardProps> = (content) => {
// should always prefer to use destructuring - and if for some reason you don't want to or cant,
// then the name should ALWAYS be `props`
+export const TooltipCopyToClipboard: FunctionComponent<TooltipCopyToClipboardProps> = ({content}) => {
```

I would probably change the props to be more dynamic to allow the caller to have 100% feature parity with CopyToClipboard.

I would not utilize useEffect, just use a timeout to know when to set the value back

```typescript
// we can extend props, we want to control one, so we don't allow that to be passed in
// https://www.typescriptlang.org/docs/handbook/utility-types.html#omittype-keys
export interface CopyToClipboardWithTooltipProps extends Omit<CopyToClipboardProps, 'copied'> {
  tooltipContent: Maybe<string | JSX.Element>;
  copiedMessage?: string;
}

export const TooltipCopyToClipboard: FunctionComponent<TooltipCopyToClipboardProps> = ({
tooltipContent,
copiedMessage = 'Copied to clipboard',
...copyToClipboardProps, // this means "put all other properties into this variable"
}) => {

const [displayContent, setDisplayContent] = useState(tooltipContent);

  const handleCopied = () => {
    setCopiedState(copiedMessage);
    setTimeout(() => {
        setCopiedState(tooltipContent);
    }, 3000) // TODO: store me in constant at top of file
  };

  return (
    <Tooltip content={displayContent}>
      <CopyToClipboard
        {...copyToClipbaordProps} // pass all other clipboard props down to component
        copied={handleCopied} // except this one, we are overridding
      />
    </Tooltip>
  );

```

2023-05-02 23:10 UTC, joiecosby commented on libs/ui/src/lib/widgets/TooltipCopyToClipboard.tsx
@paustint can you elaborate a bit more on why we would use setTimeout()? 

```
  const handleCopied = () => {
    setCopiedState(copiedMessage);
    setTimeout(() => {
        setCopiedState(tooltipContent);
    }, 3000) // TODO: store me in constant at top of file
  };

```

In CopyToClipboard, copied is dynamically setting that const to be true/false. When the CopyToClipboard is invoked, it will display the checkbox for 1.5 seconds and then revert back. Can we just use the state of the child component in this instance? So with the logic below, it was toggling correctly based off the child component. 
```
  const handleCopied = (data) => {
    setCopiedState(data);
  };

  useEffect(() => {
    if (!copiedState) {
      setDisplayContent(content.content);
    } else {
      setDisplayContent('Copied to Clipboard');
    }
  }, [handleCopied]);

  return (
    <Tooltip content={displayContent}>
      <CopyToClipboard
        icon={{ type: 'utility', icon: 'error', description: 'Click to copy to clipboard' }}
        content="test"
        className="slds-text-color_error slds-p-right_x-small"
        copied={handleCopied}
      />
    </Tooltip>
  );
```

2023-05-02 23:11 UTC, joiecosby commented on libs/ui/src/lib/widgets/TooltipCopyToClipboard.tsx
One other question, for do we want to allow the user to pass in the button type that they are looking to be displayed and pass that in as {...copyToClipboardProps}? 

```
export interface CopyToClipboardWithTooltipProps extends Omit<CopyToClipboardProps, 'copied'> {
  tooltipContent: Maybe<string | JSX.Element>;
  copiedMessage?: string;
}

export const TooltipCopyToClipboard: FunctionComponent<TooltipCopyToClipboardProps> = ({
tooltipContent,
copiedMessage = 'Copied to clipboard',
...copyToClipboardProps, // this means "put all other properties into this variable"
}) => {
```

2023-05-03 15:02 UTC, paustint commented on libs/ui/src/lib/widgets/TooltipCopyToClipboard.tsx
> can you elaborate a bit more on why we would use setTimeout()?

if `copied()` is called after the interval, then we would not need `setTimeout` in the parent, I didn't realize that was the case.

In which case I think you can do something like this - you don't need a `useEffect`, we don't need to store the child state since the function is called every time the child state changes.

> One other question, for do we want to allow the user to pass in the button type that they are looking to be displayed and pass that in as {...copyToClipboardProps}?

AFAIK we don't need to add anything new here.
`export interface CopyToClipboardWithTooltipProps extends Omit<CopyToClipboardProps, 'copied'>`

This means we combine all properties from `CopyToClipboardWithTooltipProps` (except the copied property, which we could actually allow if we wanted to) with `tooltipContent` and `copiedMessage`.

If `CopyToClipboard` does not handle a use-case we need it to, then we could make changes there, but we would not need to make any changes to `TooltipCopyToClipboard` since that just passes any the the component properties (props) down to the child.

### This is what I think it could look like - without the `useEffect`

```typescript
// we can extend props, we want to control one, so we don't allow that to be passed in
// https://www.typescriptlang.org/docs/handbook/utility-types.html#omittype-keys
export interface CopyToClipboardWithTooltipProps extends Omit<CopyToClipboardProps, 'copied'> {
  tooltipContent: Maybe<string | JSX.Element>;
  copiedMessage?: string;
}

export const TooltipCopyToClipboard: FunctionComponent<TooltipCopyToClipboardProps> = ({
tooltipContent,
copiedMessage = 'Copied to clipboard',
...copyToClipboardProps, // this means "put all other properties into this variable"
}) => {

const [displayContent, setDisplayContent] = useState(tooltipContent);

  const handleCopied = (active: boolean) => {
    setCopiedState(active ? copiedMessage : tooltipContent);
  };

  return (
    <Tooltip content={displayContent}>
      <CopyToClipboard
        {...copyToClipbaordProps} // pass all other clipboard props down to component
        copied={handleCopied} // except this one, we are overridding
      />
    </Tooltip>
  );
```

2023-05-04 01:37 UTC, paustint requested changes

2023-05-04 01:37 UTC, paustint commented on libs/ui/src/lib/widgets/TooltipCopyToClipboard.tsx
> +export interface TooltipCopyToClipboardProps extends Omit<CopyToClipboardProps, 'copied' | 'content'> {
@joiecosby - We can just use the `content` prop from `CopyToClipboardProps` instead of making this a different api

```typescript
export interface TooltipCopyToClipboardProps extends Omit<CopyToClipboardProps, 'copied'> {
  className?: string;
  icon?: IconObj;
  copiedMessage?: string;
}
...
export const TooltipCopyToClipboard: FunctionComponent<TooltipCopyToClipboardProps> = ({
  content,
  copiedMessage = 'Copied to clipboard',
  ...copyToClipboardProps
}) => {
...useState(content);...
...
...active ? copiedMessage : content...
...
<CopyToClipboard {...copyToClipboardProps} content={content} copied={handleCopied} />
```

2023-05-04 02:15 UTC, paustint commented on libs/ui/src/lib/widgets/CopyToClipboardWithToolTip.tsx
> +export interface CopyToClipboardWithToolTipProps extends Omit<CopyToClipboardProps, 'copied' | 'content'> {
@joiecosby

1. `Omit<CopyToClipboardProps, 'copied' | 'content'` you should remove `'content'` here
2. you have some properties here that are unused, which we should not have.
3. 
You should remove `className`, `content` and `icon` since these already exist with `CopyToClipboardProps`

2023-05-10 01:23 UTC, paustint approved these changes

2023-05-10 01:23 UTC, merged