See child related records from a record id #70
jetstreamapp/jetstream pull request #345
Opened 2023-05-06 01:26 UTC by paustint

This PR was branched off of #339 - so this includes changes from both PRs

Added ability to view child records for an object, all child records are dynamically subqueried

Added instrumentation for various actions on the view record modal

If a user has ever been in view mode, then we will take back to view mode if a user saves/cancel from an edit mode

Improved download process to use RecordDownloadModal which produces better output files and supports subqueries

Demo
https://jam.dev/c/c314f716-a8a2-463a-9489-8219b1ea8d46

resolves #70

2023-05-06 16:47 UTC, joiecosby commented on apps/jetstream/src/app/components/core/ViewChildRecords.tsx
> +    .filter(Boolean);
If the user has inputed other fields, will they display in the UI or is the expectation that only these fields will display?

2023-05-06 16:52 UTC, joiecosby commented on libs/shared/constants/src/lib/shared-constants.ts
>    /** AUTOMATION CONTROL */
I realized you are adding all these constants and then using them to trackEvents using the import below. Can you can explain what useAmplitude does?

import { useAmplitude } from './analytics';

2023-05-06 17:03 UTC, joiecosby commented on apps/jetstream/src/app/components/core/ViewChildRecords.tsx
> +/* eslint-disable @typescript-eslint/no-unused-vars */
Overall question for you, it looks like if I click into a related record via the lookup  and then go to child records, I see child records for both the Account and the User object. I wanted to double check that is what is expected.


![Screen Shot 2023-05-06 at 09 59 39](https://user-images.githubusercontent.com/39092797/236637424-ba34af64-6107-4f58-b0f3-852ea4815531.png)

2023-05-07 16:35 UTC, paustint commented on apps/jetstream/src/app/components/core/ViewChildRecords.tsx
> +    .filter(Boolean);
For child query, this doesn't allow a user to provide any fields - this defaults to just a few basic fields (which don't always exist for some standard objects).

So for now, only these fields display. It would be difficult to know what fields are important to display on every object since some standard objects don't have the basic fields included.

For now we allow the user to view the record in salesforce, but I was thinking it would be cool if we could somehow let the user view the entire child record without leaving Jetstream.

2023-05-07 16:37 UTC, paustint commented on libs/shared/constants/src/lib/shared-constants.ts
>    /** AUTOMATION CONTROL */
This captures telemetry data to know how users are utilizing the application. This just helps to understand what areas of the app are used and which are not used.

Currently this data isn't really utilized, but the idea is that we have data available to make product decisions based on actual user usage information.

2023-05-07 16:39 UTC, paustint commented on apps/jetstream/src/app/components/core/ViewChildRecords.tsx
> +/* eslint-disable @typescript-eslint/no-unused-vars */
It should only show child records for the current selected record, I will take a look.

2023-05-10 17:13 UTC, joiecosby requested changes
@paustint I queried out the following, navigated to the Primary Quote and went to the Child Record tab. When on the Child Record tab I see the error below. Once I navigated back to the Record tab and back to the Child Record tab, the error was gone.

`[SELECT Id From Opportunity];`

![image](https://github.com/jetstreamapp/jetstream/assets/39092797/4b26baef-3022-4def-bf91-15ea5945c42f)

2023-05-13 00:36 UTC, paustint commented
@joiecosby - Good catch on that bug you found - **this is ready for review again.** 

It is actually (IMO) A Salesforce bug because they have two child relationships with the same name, which is not allowed in any other circumstance, but somehow they have this with a native Salesforce field named `FinanceBalanceSnapshots`.

`Quote__c` UI on the query page was also broken because of this since we were using the child relationship name as a unique key. Viewing child fields and attempting to click any field on the child object `FinanceBalanceSnapshots` would select two fields.

Ended up just ignoring circumstances where the child relationship name is duplicated [ecab88a](https://github.com/jetstreamapp/jetstream/pull/345/commits/ecab88aa8ec84c7855a3f31cfdd7e58209ae9b74) - annoying because there is now a small performance hit for getting object metadata (small data set so is negligible)

<img width="608" alt="image" src="https://github.com/jetstreamapp/jetstream/assets/5461649/02f0d39c-bbf5-42c3-9bf4-c83caafaece5">

2023-05-29 21:22 UTC, merged